[phases.setup]
nixPkgs = [
  "python311Full",
  "gcc",
  "pkg-config",
  "freetype",
  "libpng"
]

[phases.install]
cmds = [
  "python -m venv /opt/venv",
  ". /opt/venv/bin/activate",
  "pip install --upgrade pip",
  "pip install -r requirements.txt"
]

[phases.start]
cmd = ". /opt/venv/bin/activate && python main.py"
